spring.application.name=WebbProjekt1
spring.thymeleaf.cache=false

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

# Include application-keys.properties for sensitive data
spring.config.import=optional:classpath:application-keys.properties


